
easy_admin:
    entities:
      Livres:
        class: App\Entity\Livres
        list:
          fields:
            - { property: 'photoTicket', type: 'image', base_path: '%app.path.ticket_image%' }
            - { property: 'photo', type: 'image', base_path: '%%app.path.photo_image%' }

        show:
          fields:
            - { property: 'photoTicket', type: 'image', base_path: '%app.path.ticket_image%' }
            - { property: 'photo', type: 'image', base_path: '%app.path.photo_image%' }

        form:
          fields:
            - { property: 'ticketFile', type: 'vich_image' }
            - { property: 'photoFile', type: 'vich_image' }
