
easy_admin:
    entities:
      Livres:
        class: App\Entity\Livres
        list:
          fields:
            - { property: 'photoTicket', type: 'image', base_path: '%app.path.ticket_image%' }
            - { property: 'photo', type: 'image', base_path: '%%app.path.photo_image%' }

        show:
          fields:
            - { property: 'photoTicket', type: 'image', base_path: '%app.path.ticket_image%' }
            - { property: 'photo', type: 'image', base_path: '%app.path.photo_image%' }

        form:
          fields:
            - { property: 'ticketFile', type: 'vich_image' }
            - { property: 'photoFile', type: 'vich_image' }



          LieuxAchat:
            class: App\Entity\LieuxAchat

          Vente:
            class: App\Entity\Vente

          User:
            class: App\Entity\User
            label: 'Utilisateurs'
            list:
                fields:
                    - { property: 'roles', label: 'Roles', type: json_array}
            form:
                fields:
                    - email
                    - { property: 'roles', label: 'Roles', type: choice, type_options: {expanded: true, multiple: true, choices: {'Utilisateur':'ROLE_USER', 'Administrateur':'ROLE_ADMIN'}}}
