vich_uploader:
    db_driver: orm

    mappings:
      ticket:
           uri_prefix: '%app.path.ticket_images%'
           upload_destination: '%kernel.project_dir%/public%app.path.ticket_images%'

      photo:
        uri_prefix: '%app.path.photo_images%'
        upload_destination: '%kernel.project_dir%/public%app.path.photo_images%'
