vich_uploader:
    db_driver: orm

    mappings:
      ticket_image:
           uri_prefix: '%app.path.ticket_image%'
           upload_destination: '%kernel.project_dir%/public/%app.path.ticket_image%'

      photo_image:
        uri_prefix: '%app.path.photo_image%'
        upload_destination: '%kernel.project_dir%/public/%app.path.photo_image%'
